---
- hosts: Local
  become: yes
  vars_files: "arquivos/var.env"
  tasks:

  - name: Print a variable
    ansible.builtin.debug:
      var: Ambiente  

  - name: Check contents for emptiness
    ansible.builtin.debug:
        msg: "Directory is empty"
    when: Ambiente == ""

- name: Verificando ambiente  DEV
  hosts: DEV
  become: yes
  vars_files: "arquivos/vars.yml"
  tasks:
    - name: Check contents for emptiness
      include_role:
        name: deployDev
      when: Ambiente == "dev"

- name: Verificando ambiente QA
  hosts: QA
  become: yes
  vars_files: "arquivos/vars.yml"
  tasks:
    - name: Check contents for emptiness
      include_role:
        name: deployQA
      when: Ambiente == "qa"

- name: Verificando ambiente PROD
  hosts: PROD
  become: yes
  vars_files: "arquivos/vars.yml"
  tasks:
    - name: Check contents for emptiness
      include_role:
        name: deployPROD
      when: Ambiente == "prod"
  



  