---
- hosts: Local
  become: yes
  tasks:
  - name: Criando repositorio 
    command: aws ecr create-repository --repository-name teste --image-scanning-configuration scanOnPush=true  --region us-east-2
  - name: gerando chave AWS  
    shell: aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin 096738690913.dkr.ecr.us-east-2.amazonaws.com/almeida
  - name: Subir a imagem para AWS
    shell: sudo docker push 096738690913.dkr.ecr.us-east-2.amazonaws.com/teste:latest
