---
- hosts: Local
  become: yes
  tasks:
  - name: Gerando Build Docker
    command: ls
  - name: BUnda
    command: sudo docker build -f workspace/DevOps/CI-CD/dockerfile -t almeida .
  - name: Taguiando a imagem
    command: docker tag almeida:latest 096738690913.dkr.ecr.us-east-2.amazonaws.com/teste:latest
  - name: apagando imagem 
    command: docker image rm -f almeida
    


  


