FROM nginx:1.15.8-alpine

COPY DevOps/nginx.conf /etc/nginx/nginx.conf

COPY DevOps/*.html /usr/share/nginx/html

RUN mkdir /usr/share/nginx/html/images

COPY DevOps/images/*.png /usr/share/nginx/html/images

