---
- hosts: Local
  become: yes
  tasks:
  - name: Gerando Build Docker
    command: docker build -f dockerfile -t almeida:1 .
  - name: Executando container 
    command: docker run -it -d almeida:1

  


