---
- hosts: Local
  become: yes
  tasks:
  - name: Gerando Build Docker
    command: docker build -f dockerfile -t almeida .
  - name: Executando container 
    command: docker run --name build --rm -it -d almeida
  - name: Copiando arquivo
    command: docker cp . build:/App 
  


