---
- name: Criando Build
  hosts: Local
  #become: yes #sobe para usurio priveligiado 
  tasks:
  - name: Instalar servidor web Nginx
    sudo: yes
    yum: name=python-pip state=present

  - name: Install Docker
    sudo: yes
    yum: name:docker state=latest update_cache=yes

  - name: Star Docker 
    sudo : yes
    service: name=docker state=started args='--storage-opt dm.basesize=20G'
  
  
    